import {
  AddOne,
  AddPicture,
  Aiming,
  Alarm,
  AllApplication,
  ArrowRight,
  Book,
  BookOne,
  Bookmark,
  Box,
  Buy,
  Bug,
  Camera,
  Caution,
  ChartHistogram,
  ChartLine,
  ChartPie,
  CheckOne,
  Clipboard,
  CloseSmall,
  CloudyNight,
  Comment,
  Components,
  Compass,
  Config,
  Copy,
  CrossRing,
  CubeThree,
  DashboardOne,
  Data,
  DataFile,
  Delete,
  Diamond,
  Down,
  Download,
  Drag,
  Edit,
  Eyes,
  FSevenKey,
  Filter,
  Fire,
  Flask,
  Folder,
  FolderOpen,
  Forbid,
  Formula,
  FullScreen,
  GamePs,
  GameHandle,
  Ghost,
  Gift,
  Github,
  GridFour,
  GridNine,
  GridSixteen,
  Headset,
  Heart,
  Home,
  Hourglass,
  Info,
  Key,
  Keyboard,
  Leaf,
  Left,
  Level,
  Lightning,
  Like,
  Link,
  LinkOne,
  ListView,
  Lock,
  Magic,
  MagicWand,
  Mail,
  MenuFold,
  MenuUnfold,
  Message,
  MicrophoneOne,
  Minus,
  Mirror,
  Moon,
  Mouse,
  Music,
  Notebook,
  PauseOne,
  Pencil,
  Phone,
  Picture,
  Pin,
  Planet,
  PlayOne,
  Plus,
  Power,
  PreviewClose,
  PreviewOpen,
  Refresh,
  ReplayMusic,
  Right,
  Rocket,
  Ruler,
  Save,
  Scissors,
  Search,
  Send,
  Setting,
  SettingConfig,
  Share,
  Shield,
  ShoppingCart,
  Skull,
  SmilingFace,
  Snowflake,
  SortFour,
  SortThree,
  SpeedOne,
  Star,
  SunOne,
  Tag,
  TagOne,
  Target,
  Text,
  ThumbsUp,
  Time,
  Tool,
  Translate,
  Tree,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlock,
  Up,
  Upload,
  Video,
  VolumeNotice,
  Wallet,
  Water,
  Write,
} from '@icon-park/react'
import { pluginIdFromAction, RADIAL_PLUGIN_ICON, type RadialAction } from '@shared/contracts/radial'

/** Curated IconPark subset for radial slices. Explicit record (not import *)
 *  so tree-shaking keeps the bundle to just these. */
export const RADIAL_ICONS = {
  Setting,
  CloseSmall,
  ChartHistogram,
  Flask,
  Buy,
  AllApplication,
  Search,
  Github,
  Refresh,
  AddOne,
  Drag,
  AddPicture,
  Link,
  FullScreen,
  Minus,
  Pin,
  GridFour,
  GridNine,
  GridSixteen,
  Down,
  Up,
  Right,
  Left,
  TrendingUp,
  TrendingDown,
  PreviewOpen,
  PreviewClose,
  SortFour,
  SortThree,
  Save,
  Plus,
  FSevenKey,
  Magic,
  Diamond,
  LinkOne,
  Level,
  ListView,
  Components,
  Forbid,
  CheckOne,
  Caution,
  Info,
  Star,
  ArrowRight,
  MenuFold,
  MenuUnfold,
  SettingConfig,
  Mirror,
  Filter,
  Home,
  Message,
  Comment,
  Mail,
  Delete,
  Edit,
  Copy,
  Clipboard,
  Lightning,
  Fire,
  Shield,
  Key,
  Lock,
  Unlock,
  Eyes,
  Aiming,
  Compass,
  Rocket,
  Trophy,
  Gift,
  Alarm,
  Time,
  Hourglass,
  Bug,
  Tool,
  Config,
  Data,
  DataFile,
  Book,
  BookOne,
  Notebook,
  Bookmark,
  Tag,
  TagOne,
  Folder,
  FolderOpen,
  Picture,
  Camera,
  Video,
  Music,
  Headset,
  GamePs,
  GameHandle,
  Keyboard,
  Mouse,
  Wallet,
  ShoppingCart,
  Box,
  CubeThree,
  Planet,
  Moon,
  SunOne,
  CloudyNight,
  Snowflake,
  Leaf,
  Tree,
  Water,
  Heart,
  Like,
  ThumbsUp,
  SmilingFace,
  Ghost,
  Skull,
  CrossRing,
  Target,
  DashboardOne,
  SpeedOne,
  Send,
  Share,
  Download,
  Upload,
  Power,
  PlayOne,
  PauseOne,
  ReplayMusic,
  VolumeNotice,
  MicrophoneOne,
  Phone,
  ChartLine,
  ChartPie,
  Formula,
  Text,
  Translate,
  Write,
  Pencil,
  Scissors,
  Ruler,
  MagicWand,
} as const

export type RadialIconName = keyof typeof RADIAL_ICONS
export const RADIAL_ICON_NAMES = Object.keys(RADIAL_ICONS).sort() as RadialIconName[]

export function radialIcon(name: string): (typeof RADIAL_ICONS)[RadialIconName] {
  return RADIAL_ICONS[name as RadialIconName] ?? RADIAL_ICONS.AllApplication
}

/** Default icon per action, used by seeding and when the action of a slice
 *  changes. Every id in APP_MACRO_DEFS gets an entry; plugin actions and
 *  unknown ids fall back to Components. */
const APP_MACRO_ICONS: Record<string, RadialIconName> = {
  openSettings: 'Setting',
  openAudit: 'ChartHistogram',
  openDust: 'Magic',
  openDivCards: 'Diamond',
  openRegex: 'Search',
  openWiki: 'BookOne',
  openPoeDb: 'DataFile',
  pasteRegex: 'Clipboard',
  useSavedRegex: 'Save',
  closeOverlay: 'CloseSmall',
  toggleWhiteboard: 'Write',
  toggleRegexRemote: 'Components',
}

/** The icon a NEW slice gets for an action, which is not the same question as
 *  defaultIconFor. A plugin action defaults to the plugin's own art (the
 *  RADIAL_PLUGIN_ICON sentinel, drawn as a circular badge); everything else gets
 *  a curated glyph. Split out so defaultIconFor can stay RadialIconName-typed -
 *  the sentinel is deliberately NOT a member of that union, because it is not a
 *  glyph and nothing that resolves glyphs should have to think about it. */
export function defaultSliceIcon(action: RadialAction): string {
  return pluginIdFromAction(action) ? RADIAL_PLUGIN_ICON : defaultIconFor(action)
}

export function defaultIconFor(action: RadialAction): RadialIconName {
  switch (action.kind) {
    case 'filter':
      return 'Filter'
    case 'pricecheck':
      return 'Buy'
    case 'chat':
      return 'Message'
    case 'cheatsheet':
      return 'AllApplication'
    case 'appmacro':
      return APP_MACRO_ICONS[action.action] ?? 'Components'
  }
}
