import { WRAECLAST_CARDS_URL, WRAECLAST_DROP_RATES_INDEX } from '@shared/endpoints'
import bundledSnapshot from '@shared/data/economy/div-card-weights.json'
import type { DivCard } from './types'

/** Payload shape this build understands. wraeclast.cards bumps schema_version
 *  when the card record changes; on a mismatch we keep the bundled snapshot
 *  rather than guess at unfamiliar fields. */
export const WEIGHTS_SCHEMA_VERSION = 6

/** Minimum observed stacked-deck openings before a league's community weights
 *  are trusted. A fresh league starts near zero, publishes no datamined
 *  reference weights to fall back on, and its early sample is noise in exactly
 *  the rare, high-value cards that dominate map EV -- Ancestors (7,846
 *  openings) moves 90 of 100 maps and doubles the top map's EV against the
 *  mature snapshot. Below this floor the bundled snapshot is the better data.
 *  Mature leagues sit at 1.06M (Allflame) and 4.2M (Mirage); thin ones at 31k
 *  (Keepers) and 7.8k (Ancestors). */
export const MIN_OBSERVED_TOTAL = 250_000

/** Resolved drop weight per card name. */
export type CardWeights = Record<string, number>

/** Collapse a wraeclast drop-rate payload -- remote response or bundled
 *  snapshot, they share a shape -- to `name -> weight`. Prefers the
 *  community's observation-corrected weight and falls back to the datamined
 *  reference, which covers the handful of ultra-rare cards whose community
 *  estimate rounds to 0. Returns null for anything this build cannot vouch
 *  for, so the caller can fall back. */
export function parseWeightsPayload(payload: unknown): CardWeights | null {
  const p = payload as { schema_version?: unknown; cards?: unknown } | null
  if (!p || typeof p !== 'object') return null
  if (p.schema_version !== WEIGHTS_SCHEMA_VERSION) return null
  if (!Array.isArray(p.cards)) return null

  const out: CardWeights = {}
  for (const entry of p.cards) {
    const c = entry as { name?: unknown; community_estimated_weight?: unknown; reference_weight?: unknown } | null
    if (!c || typeof c.name !== 'string') continue
    const community = typeof c.community_estimated_weight === 'number' ? c.community_estimated_weight : 0
    const reference = typeof c.reference_weight === 'number' ? c.reference_weight : 0
    const weight = community > 0 ? community : reference
    if (weight > 0) out[c.name] = weight
  }
  return Object.keys(out).length > 0 ? out : null
}

/** Offline floor, refreshed by `npm run sync-league`. */
export const BUNDLED_WEIGHTS: CardWeights = parseWeightsPayload(bundledSnapshot) ?? {}

/** Pick the live PoE1 league file out of the drop-rates index. Card weights
 *  are global game data and the per-league files are just observation buckets,
 *  so we never match the player's league: "Hardcore Allflame" would miss, and
 *  a Standard player would land on a dead league's stale weights. */
export function pickCurrentLeagueUrl(index: unknown): string | null {
  const i = index as { schema_version?: unknown; games?: { poe1?: { leagues?: unknown } } } | null
  if (!i || typeof i !== 'object') return null
  if (i.schema_version !== WEIGHTS_SCHEMA_VERSION) return null
  const leagues = i.games?.poe1?.leagues
  if (!Array.isArray(leagues)) return null
  const live = leagues.find((l) => !!l && typeof l === 'object' && !(l as { historical?: boolean }).historical) as
    | { url?: unknown; observed_total?: unknown }
    | undefined
  if (typeof live?.observed_total !== 'number' || live.observed_total < MIN_OBSERVED_TOTAL) return null
  return typeof live.url === 'string' && live.url.startsWith('/') ? live.url : null
}

/** Hand-curated weights that outrank both datasets. Only for cards neither
 *  source gets right -- wraeclast covers nothing outside the stacked deck pool,
 *  and both `div-cards.json` and `div-card-weights.json` are regenerated by
 *  `npm run sync-league`, so an edit to either is lost on the next sync. This
 *  is the only durable home for a correction. Mirrors the `priceOverrides` map
 *  in DivCardExplorer for cards with unreliable ninja prices. */
export const WEIGHT_OVERRIDES: CardWeights = {
  // Graveyard / Sanctuary only, so absent from the stacked deck pool; Maps of
  // Exile carries 5.
  Damnation: 4,
}

/** Apply wraeclast weights over the Maps of Exile card records. Cards outside
 *  the stacked deck pool -- league and boss restricted drops -- keep their MoE
 *  weight and are marked so the UI can flag them as uncorrected. Curated
 *  overrides win over both and carry no marker: they are a deliberate
 *  correction, not an uncorrected fallback. */
export function resolveWeights(cards: DivCard[], weights: CardWeights): DivCard[] {
  return cards.map((c) => {
    const override = WEIGHT_OVERRIDES[c.name]
    if (override > 0) return { ...c, weight: override, weightSource: 'override' as const }
    const w = weights[c.name]
    if (w > 0) return { ...c, weight: w, weightSource: 'wraeclast' as const }
    // Only claim a Maps of Exile weight when there actually is one -- the cards
    // with no weight in either dataset must not carry the marker.
    if (c.weight != null && c.weight > 0) return { ...c, weightSource: 'mapsofexile' as const }
    return { ...c }
  })
}

/** Fetch the live league's weights, or null if anything at all is off -- the
 *  caller then keeps the bundled snapshot. Deliberately silent: a network blip
 *  must not surface an error in a tab that renders fine without it. */
export async function fetchRemoteWeights(): Promise<CardWeights | null> {
  try {
    const ires = await fetch(WRAECLAST_DROP_RATES_INDEX)
    if (!ires.ok) return null
    const leagueUrl = pickCurrentLeagueUrl(await ires.json())
    if (!leagueUrl) return null
    const dres = await fetch(WRAECLAST_CARDS_URL + leagueUrl)
    if (!dres.ok) return null
    const remote = parseWeightsPayload(await dres.json())
    if (!remote) return null
    // A truncated regeneration would silently demote hundreds of cards to their
    // Maps of Exile weight, so require the remote to cover what the bundle does.
    if (Object.keys(remote).length < Object.keys(BUNDLED_WEIGHTS).length * 0.8) return null
    return remote
  } catch {
    return null
  }
}
